# Use Ubuntu Xenial
dist: xenial

# Use OpenJDK 11
language: java
jdk: openjdk11

# Cache .m2 directory
cache:
  directories:
    - $HOME/.m2

# Skip installation. Since we cannot fully separate installing dependencies
# from either testing or deployment, mainly for caching and time-saving
# purposes, we might as well try and come up with creative ways to lump all of
# the fetching of dependencies into the testing phase.
install: skip

# Try packaging the project as a test
script: ./mvnw -B -V verify

# Do deployment once test is successful
deploy:
  skip_cleanup: true
  on:
    tags: true
  provider: script
  script: travis/deploy.sh
